import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    manifest: "/manifest.json",
    title: "Cari Hati",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`bg-primary text-white ${poppins.className}`}>
                <div className="w-full min-h-screen mx-auto max-w-[480px] min-[480px]:border min-[480px]:border-gray-800 z-[1] bg-primary shadow-[#242424] shadow-lg">
                    {children}
                </div>
            </body>
        </html>
    );
}
