import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { AuthProvider } from "@/contexts/auth";
import { AxiosProvider } from "@/utils/requester/AxiosProvider";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    manifest: "/manifest.json",
    title: "Cari Hati",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`bg-primary text-white overflow-hidden ${poppins.className}`}
            >
                <AuthProvider>
                    <AxiosProvider>
                        <Providers>{children}</Providers>
                    </AxiosProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
