import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    manifest: "/manifest.json",
    title: "Cari Hati",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`bg-primary text-white overflow-hidden ${poppins.className}`}>
                <Providers>
                    <main className="dark w-full min-h-screen mx-auto max-w-[448px] min-[448px]:border min-[480px]:border-gray-800 z-[1] bg-primary shadow-[#242424] shadow-lg">
                        {children}
                    </main>
                </Providers>
            </body>
        </html>
    );
}
